stages:
  cleaning:
    cmd: python src/cleaning.py
    deps:
      - data/sim_slice.npy
      - data/seismic_slice.npy
      - data/seismic_slice_GT.npy
      - src/cleaning.py
    outs:
      - outputs/sim_clean.npy
      - outputs/seismic_slice_clean.npy
      - outputs/seismic_slice_GT_clean.npy

  training:
    cmd: python src/training.py
    deps:
      - outputs/sim_clean.npy
      - src/training.py
    outs:
      - outputs/X.npy
      - outputs/y.npy
      - outputs/model.pkl

  inference:
    cmd: python src/inference.py
    deps:
      - outputs/model.pkl
      - data/seismic_slice.npy
      - src/inference.py
    outs:
      - outputs/seis_estimated.npy

  evaluation:
    cmd: python src/evaluation.py
    deps:
      - outputs/seis_estimado.npy
      - outputs/sim_clean.npy
      - data/seismic_slice_GT.npy
      - src/evaluation.py
      - src/modulo/aula3_modulo_mlops.py
    outs:
      - outputs/residuos.npy
