channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.1.1
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
